### PR TITLE
feature: check if word is in english dictionary or a variant of it and use faster concurent data structures for typo tolerance

### PR DESCRIPTION
**Pull request by densumesh**

### CODE REVIEW

**Comment by skeptrunedev** [comment]
Made a change to add a section for typo tolerance: 
image

**Review by skeptrunedev — DISMISSED** [review]
+466,893 lmao :skull: 

Holy hell this is working great tho

**Comment by densumesh** [comment]
image

**Review by skeptrunedev — APPROVED** [review]
CI action for redoc will have to get fixed later

**Pull request merged**
