### PR TITLE
feature: support SSO authentication with keycloak

### LINKED ISSUE #1697: feature: support SSO authentication with keycloak
### Description

SSO is a big security win for those who have it and use the cloud version. It should be supported. 

What needs modification is the realm-export.json file for keycloak. The SSO support should all be internal to keycloak and not related to the actual Rust server.

### Target(s)

`server`

### Requirement to close

PR to add SSO into the Keycloak config which loads when the docker image starts. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

### PR DESCRIPTION
**Pull request by varshith257**
fixes #1697
/claim #1697

Related maintainer: @skeptrunedev

### CODE REVIEW

**Comment by varshith257** [comment]
@skeptrunedev Have a look into it. If they are in the right direction of requirements will incorporate other changes too. 

I will incorporate any suggestions or changes required to align with the expectations

**Comment by varshith257** [comment]
PS: This changes may contains some format and lint issues as my rust toolchain had blocked. Resolving it and will fix them soon :)

**Comment by varshith257** [comment]
@skeptrunedev Have a look into this when you have free time

**Comment by skeptrunedev** [comment]
I don't think this is on the right track. The actual Rust code should not require any modification. 

What needs modification is the `real-export.json` file for keycloak. The SSO support should all be internal to keycloak and not related to the actual Rust server. 

Going to close this for now.

**Pull request closed without merging**
