### PR TITLE
fix: multistring input for default questions on public page

### PR DESCRIPTION
**Pull request by drew-harris**

### CODE REVIEW

**Comment by drew-harris** [comment]
https://github.com/devflowinc/trieve/issues/2668

**Comment by drew-harris** [comment]
image

**Comment by drew-harris** [comment]
image

**Review by cdxker — CHANGES_REQUESTED** [review]
not-persisted

Looks great, seems like the options don't persist on page refresh

**Review by cdxker — APPROVED** [review]

**Pull request merged**
