### PR TITLE
feature: use native-tls in ureq requests to trust system TLS certs

### PR DESCRIPTION
**Pull request by adtac**
@skeptrunedev @cdxker 

This PR makes `ureq` use the `native-tls` feature so that the distro-supplied TLS certificates are trusted.

The following change captures the gist of this PR:

image

I believe all instances of `ureq::get`, `ureq::post`, etc. have been changed, but if there's anything missing / if this PR doesn't match your code style, feel free to close it and incorporate the changes in a new PR :)

### CODE REVIEW

**Comment by cdxker** [comment]
Great, going to build and test to see if this works with subtrace enabled now! Should we also up our subtrace version in this pr?

**Comment by adtac** [comment]
Nope, everything should work with the old version of subtrace. You can remove the `-tls=false`, of course ;)

**Comment by adtac** [comment]
(forgot a couple of `use std::sync::Arc` statements, amended the commit)

**Comment by cdxker** [comment]
@adtac In this project we use both `ureq` and `reqwests` do we need to do something similar here for `reqwests`?

**Comment by adtac** [comment]
`reqwest` works fine with subtrace, it's just `ureq` that causes problems with its bundled TLS certs (from `rustls`)

**Comment by cdxker** [comment]
Great, just made a few modifications to fix all the rust errors, can you cherry-pick this commit. From https://github.com/devflowinc/trieve/commit/505ef43464738f4b9076ea9a0359a5dd90f4c430

505ef43464738f4b9076ea9a0359a5dd90f4c430

**Comment by adtac** [comment]
cherry picked, rebased onto latest main

**Comment by adtac** [comment]
fixed the unused `std::sync::Arc` error

**Comment by cdxker** [comment]
Just built a docker image @ `trieve/server:native-tls-subtrace` . I don't have time to test right now, but noting the image tag here for when I have time to evaluate.

Also note that the default run command is not subtrace. You will need set your run command to this. https://github.com/devflowinc/trieve/blob/a225fe31f9bfbd58bbdbaa28c66c61baf18234fa/helm/templates/server-deployment.yaml#L36-L46

**Review by skeptrunedev — APPROVED** [review]

**Comment by adtac** [comment]
I believe https://github.com/devflowinc/trieve/pull/2988/commits/d9172d7121aa4431187aada50d52bff6b250da3c will fix https://github.com/devflowinc/trieve/actions/runs/12424254684/job/34689358734?pr=2988

**Comment by cdxker** [comment]
> I believe https://github.com/devflowinc/trieve/commit/d9172d7121aa4431187aada50d52bff6b250da3c will fix > https://github.com/devflowinc/trieve/actions/runs/12424254684/job/34689358734?pr=2988

Yes, it should can you add that into this PR. Testing environment works with Subtrace!!!

**Review by cdxker — APPROVED** [review]

**Pull request merged**
