### PR TITLE
feat: add navbar to public page

### PR DESCRIPTION
**Pull request by drew-harris**
image

### CODE REVIEW

**Comment by drew-harris** [comment]
Fixing code indent!!!

**Comment by drew-harris** [comment]
image

**Comment by drew-harris** [comment]
Fixing issues with hero background

**Comment by skeptrunedev** [comment]
- [ ] social links just icons
- [ ] meet with sales as text for cal booking and make it an action button similar to the Github star on pdf2md or sign up on trieve.ai 
- [ ] humans@trieve.ai as mailto instead of 'email us' text
- [ ] phone icon instead of 'call us'

**Comment by drew-harris** [comment]
image

**Review by skeptrunedev — APPROVED** [review]

**Pull request merged**
