### PR TITLE
feature: add new TS client lib to repo

### PR DESCRIPTION
**Pull request by SaraVieira**
Creates a new SDK for trieve to be used in TS/JS

Very much a WIP

Example ussage:

```
	const trieve = new TrieveSDK({
      apiKey: "tr-mKHF9sstPHQHcCbh6Qk6Uw54hx7uwDGU",
      datasetId: "c04c43d9-382d-4815-810d-b776904a7390",
    });
    const data = await trieve.search({
      query: "one",
      search_type: "hybrid",
    });
```

Methods:

- [x] chunk
- [x] groups
- [x] topic
- [x] message
- [x] file
- [x] analytics
- [x] events
- [x] docs (example: https://trieve-sdk-docs.surge.sh/)

### CODE REVIEW

**Comment by skeptrunedev** [comment]
Should not get merged yet since some tests are not passing yet and there are still a lot of routes left to go

**Review by skeptrunedev — COMMENTED** [review]
Hmmm, not sure why lint for search and analytics is broken. Going to take a look at that and simplifying the commit history here then will merge.

**Comment by SaraVieira** [comment]
Hm, these don't seem to run on main so they may be failing there too :/

**Comment by skeptrunedev** [comment]
There was a merge in the commit history which took me a minute to fix. Should be in a good state now. Looking at CI again

**Comment by skeptrunedev** [comment]
I may have mangled some things, but I removed files until it was in a state where CI actions could pass

**Review by skeptrunedev — APPROVED** [review]

**Pull request merged**
