### PR TITLE
feature: clear chat history in search component

### PR DESCRIPTION
**Pull request by cdxker**
clear-chat

### CODE REVIEW

**Review by skeptrunedev — CHANGES_REQUESTED** [review]
Flip the sides of powered and clear buttons

**Comment by SaraVieira** [comment]
@skeptrunedev If we switch the sides it's gonna look off on search. I would just make the button less prominent, add a border instead of a bg color

**Comment by skeptrunedev** [comment]
> @skeptrunedev If we switch the sides it's gonna look off on search. I would just make the button less prominent, add a border instead of a bg color

Sounds like a great plan to me

**Comment by SaraVieira** [comment]
image

Made some small chanmges

- Button only appears when there are messages
- Added colors for dark mode
- Removed bg color and added a border instead

**Review by skeptrunedev — APPROVED** [review]
LGTM

**Pull request merged**
