### PR TITLE
feature: Click-through Rate frontend page

### PR DESCRIPTION
**Pull request by drew-harris**

### CODE REVIEW

**Comment by drew-harris** [comment]
image

**Comment by skeptrunedev** [comment]
How did you add seed data to test? Not sure how to go about that

**Comment by drew-harris** [comment]
> How did you add seed data to test? Not sure how to go about that

https://github.com/drew-harris/trieve-testing/blob/main/src/populateCTR.ts

**Review by skeptrunedev — APPROVED** [review]
Removed some comments, but otherwise seems good. Tested and the data does show.

**Pull request merged**
