### PR TITLE
feature: support SSO authentication with keycloak 

### PR DESCRIPTION
**Pull request by varshith257**
fixes https://github.com/devflowinc/trieve/issues/1697

Related maintainer: @skeptrunedev

### CODE REVIEW

**Comment by varshith257** [comment]
@skeptrunedev This is the follow-up to our discussion in the discord. I am more interested in completing this issue.  If any changes/suggestions are given, I am more happy to incorporate them

**Comment by skeptrunedev** [comment]
What were the steps you used to test this?

**Comment by varshith257** [comment]
@skeptrunedev  As you told you will test itin our conversation. I didn't made a way to test it 😅

**Comment by skeptrunedev** [comment]
Just tried starting keycloak with this new realm-export and it did not work: 

```
keycloak  | 2024-07-09 04:46:10,547 INFO  [org.keycloak.exportimport.singlefile.SingleFileImportProvider] (main) Full importing from file /opt/keycloak/bin/../data/import/realm-export.json
keycloak  | 2024-07-09 04:46:10,608 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
keycloak  | 2024-07-09 04:46:10,608 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "clientId" (class org.keycloak.representations.idm.RoleRepresentation), not marked as ignorable (9 known properties: "clientRole", "composite", "scopeParamRequired", "id", "description", "attributes", "name", "composites", "containerId"])
keycloak  |  at [Source: (ByteArrayInputStream); line: 404, column: 24] (through reference chain: org.keycloak.representations.idm.RealmRepresentation["roles"]->org.keycloak.representations.idm.RolesRepresentation["client"]->java.util.LinkedHashMap["account"]->java.util.ArrayList[8]->org.keycloak.representations.idm.RoleRepresentation["clientId"])
keycloak  | 2024-07-09 04:46:10,608 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unrecognized field "clientId" (class org.keycloak.representations.idm.RoleRepresentation), not marked as ignorable (9 known properties: "clientRole", "composite", "scopeParamRequired", "id", "description", "attributes", "name", "composites", "containerId"])
keycloak  |  at [Source: (ByteArrayInputStream); line: 404, column: 24] (through reference chain: org.keycloak.representations.idm.RealmRepresentation["roles"]->org.keycloak.representations.idm.RolesRepresentation["client"]->java.util.LinkedHashMap["account"]->java.util.ArrayList[8]->org.keycloak.representations.idm.RoleRepresentation["clientId"])
keycloak  | 2024-07-09 04:46:10,608 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
keycloak exited with code 1
```

Going to close for now pending some testing with proven successful start of keycloak via docker at least.

**Comment by varshith257** [comment]
@skeptrunedev  Will update on this

**Pull request closed without merging**
