### PR TITLE
feature: typo tolerance

### PR DESCRIPTION
**Pull request by aaryanpunia**
When spinning up services the amount of word_workers > bktree_workers. If dealing with big datasets spin up word_workers to 15+ to accommodate load CH can take the abuse

### CODE REVIEW

**Review by cdxker — CHANGES_REQUESTED** [review]
Can we change id-worker to a better name and include `cronjob` instead of worker

**Comment by aaryanpunia** [comment]
Pending problems - 

1. In word-worker, somehow, when inserting in the relation table, we are inserting the same (dataset_id, word_id) tuple multiple times in a single call to Postgres, this is not allowed when utilizing an on conflict do update.
2. Deadlocks with multiple word-workers, solvable by utilizing clickhouse instead of Postgres.

**Review by cdxker — CHANGES_REQUESTED** [review]
Recursive data structure is too deep, getting "bk tree depth limit exceeded" serde errror when trying to load into the server. Will need to store the tree as a different structure. First thing that comes to mind is an adjacency list.

**Review by cdxker — APPROVED** [review]

**Review by cdxker — CHANGES_REQUESTED** [review]
Can it return the corrected query on the response?

**Review by cdxker — APPROVED** [review]

**Pull request merged**
