### PR TITLE
feature: make chat UX for modal component more chat-like 

### PR DESCRIPTION
**Pull request by SaraVieira**
- [x]  feature: change chat UX to have input at bottom
- [x]  feature: add text describing what the bot does above the query suggestions
- [x]  feature: add query suggestion buttons
- [x]  feature: add refresh button to query suggestions
- [x]  feature: add toggle replacing button at top of search results for chat
image
image

image
image

closes https://github.com/devflowinc/trieve/issues/2416

### CODE REVIEW

**Comment by skeptrunedev** [comment]
Spent, longer on this then I probably should have, but sanded it and think we should make some more changes to the chat UX.

- [ ] refactor: show chat messages in ascending order instead of descending
- [ ] feature: show user icon next to user messages (and tag in mobile)
- [ ] feature: full-screen chat in mobile
- [ ] feature: add clear button when messages are present

image
image

**Review by skeptrunedev — CHANGES_REQUESTED** [review]
requests spec'ed in comment above

**Comment by densumesh** [comment]
image

**Review by skeptrunedev — CHANGES_REQUESTED** [review]
image

image

- [ ] feat: start chat with user message when the switcher in results is clicked
- [x] cleanup: scrolling system for chat UX

**Comment by SaraVieira** [comment]
Moved the clear button to its own issue here: https://github.com/devflowinc/trieve/issues/2459

**Review by cdxker — CHANGES_REQUESTED** [review]
image

Scroll bar shouldn't go down this far. 

image

I think this is also causing issues on mobile view.

**Comment by SaraVieira** [comment]
@cdxker Fixed mobile and also made the window scroll when you get new messages

**Review by cdxker — APPROVED** [review]

**Pull request merged**
